export { default as useLocalStore } from './src/hook/useLocalStore'
export { default as useLazyRequest } from './src/hook/useLazyRequest'
export { default as usePager } from './src/hook/usePager'
export { setApiKeyMethod } from './src/hook/usePager'
export { default as useDict } from './src/hook/useDict'

export { default as xiaohan } from './src/svc/statisticSvc'

export { default as storage } from './src/util/storage'
export { default as getUid } from './src/util/getUid'
export { default as convertBase64UrlToBlob } from './src/util/convertBase64UrlToBlob'
export { default as dealImage } from './src/util/dealImage'
export { default as eventBus } from './src/util/eventBus'
export { default as getVideoCoverAndDuration } from './src/util/getVideoCoverAndDuration'
export { default as transTime } from './src/util/transTime'
export { default as message } from './src/util/message'
export { default as copy } from './src/util/copy'
export { default as loadScript } from './src/util/loadScript'
export { default as openModal } from './src/util/openModal'
export { setModalContainer } from './src/util/openModal'
export { default as Qs } from './src/util/queryString'
